---
- name: Ensure /etc/simplevm/scripts/users directory exists
  file:
    path: /etc/simplevm/scripts/users
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy add_keys.sh to /etc/simplevm/script/users
  copy:
    src: add_keys.sh
    dest: /etc/simplevm/scripts/users/add_keys.sh
    owner: root
    group: root
    mode: '0755'
  
- name: Ensure /etc/simplevm/scripts/utils directory exists
  file:
    path: /etc/simplevm/scripts/utils
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy check_version.sh to /etc/simplevm/scripts/utils
  copy:
    src: check_version.sh
    dest: /etc/simplevm/scripts/utils/check_version.sh
    owner: root
    group: root
    mode: '0755'

- name: Copy update_compatibilities.sh to /etc/simplevm/scripts/utils
  copy:
    src: update_compatibilities.sh
    dest: /etc/simplevm/scripts/utils/update_compatibilities.sh
    owner: root
    group: root
    mode: '0755'
  
- name: Ensure /etc/simplevm/config directory exists
  file:
    path: /etc/simplevm/config
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure /var/log directory exists
  file:
    path: /var/log
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create metadata.log if it does not exist
  file:
    path: /var/log/metadata.log
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Copy metadata-service.service to /etc/systemd/system
  copy:
    src: ./metadata-service.service
    dest: /etc/systemd/system/metadata-service.service
    owner: root
    group: root
    mode: '0644'

- name: Copy metadata-service.timer to /etc/systemd/system
  copy:
    src: ./metadata-service.timer
    dest: /etc/systemd/system/metadata-service.timer
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon to recognize new service and timer files
  command: systemctl daemon-reload

- name: Enable and start metadata-service.service
  systemd:
    name: metadata-service.service
    enabled: yes
    state: started

- name: Enable and start metadata-service.timer
  systemd:
    name: metadata-service.timer
    enabled: yes
    state: started

- name: Ensure AuthorizedKeysFile is configured in sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AuthorizedKeysFile'
    line: 'AuthorizedKeysFile .ssh/authorized_keys /home/%u/.ssh/authorized_keys /home/%u/.ssh/metadata_authorized_keys'
    state: present
  notify: Restart ssh
