---


- name: Debug reprepro commands
  debug:
    msg:
      - "reprepro -b {{ repo_base_dir }}/{{item.0}} includedeb {{item.0}} {{ remote_package_dir }}/{{ item.1 }}.deb"
  loop: "{{ releases | product(packages) | list }}"
- name: Add packages to apt repository
  become: true
  shell: >
    reprepro -b {{ repo_base_dir }}/{{item.0}} includedeb {{item.0}} {{ remote_package_dir }}/{{ item.1 }}.deb
  loop: "{{ releases | product(packages) | list }}"
  register: reprepro_result
  ignore_errors: yes
  when: not (dev | default(false))


- name: Debug reprepro dev-package commands
  debug:
    msg:
      - "reprepro -b {{ repo_base_dir }}/dev/{{item.0}} includedeb {{item.0}} {{ remote_package_dir }}_dev/{{ item.1 }}_dev.deb"
  loop: "{{ releases | product(packages) | list }}"

- name: Add dev-packages to dev-apt repository
  become: true
  shell: >
    reprepro -b {{ repo_base_dir }}/dev/{{item.0}} includedeb {{item.0}} {{ remote_package_dir }}_dev/{{ item.1 }}_dev.deb
  loop: "{{ releases | product(packages) | list }}"
  register: reprepro_result
  ignore_errors: yes
  when: dev | default(false)


- name: Check reprepro output
  debug:
    msg: "Warning: Package {{item.item}} already exists with different content; skipping."
  loop: "{{reprepro_result.results}}"
  when: item.stderr is defined and "cannot be included as" in item.stderr