---

- name: Debug variable values
  debug:
    msg:
      - "Branch Name: {{ branch_name }}"
      - "Repository URL: {{ repo_url }}"
      - "Local Build Directory: {{ local_build_dir }}"

- name: Ensure local build directory exists
  file:
    path: "{{ local_build_dir }}"
    state: directory

- name: Clone the repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ local_build_dir }}"
    version: "{{ branch_name }}"

- name: Build Debian package - {{ item }}
  command: "dpkg-deb --build {{ local_build_dir }}/packages/{{ item }}"
  loop: "{{ packages }}"

- name: Transfer packages to remote server
  include_tasks: transfer_packages.yml