---
- name: Ensure local build directory exists
  file:
    path: "{{ local_build_dir }}"
    state: directory

- name: Clone the repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ local_build_dir }}"
    version: "{{ branch_name }}"

- name: Build Debian package - {{ item }}
  command: "dpkg-deb --build {{ local_build_dir }}/packages/{{ item }}"
  with_items:
    - core
    - meta
    - users

- name: Transfer packages to remote server
  include_tasks: transfer_packages.yml