---

- name: Ensure remote package directory exists
  ansible.builtin.file:
    path: "{{ remote_package_dir }}"
    state: directory
  delegate_to: "{{ inventory_hostname }}"

- name: Ensure remote dev-package directory exists
  ansible.builtin.file:
    path: "{{ remote_package_dir }}_dev"
    state: directory
  delegate_to: "{{ inventory_hostname }}"


- name: Copy Debian packages to remote server
  ansible.builtin.copy:
    src: "{{ local_build_dir }}/packages/{{ item }}.deb"
    dest: "{{ remote_package_dir }}"
  with_items:
    - core
    - meta
    - users
    - updater
  delegate_to: "{{ inventory_hostname }}"
  when: not(dev | default(false))


- name: Copy Dev Debian packages to remote server
  ansible.builtin.copy:
    src: "{{ local_build_dir }}/packages/{{ item }}_dev.deb"
    dest: "{{ remote_package_dir }}_dev"
  with_items:
    - core_dev
    - meta_dev
    - users_dev
    - updater_dev
  delegate_to: "{{ inventory_hostname }}"
  when: dev | default(false)