---
- name: "Retrieve GPG passphrase from control machine"
  delegate_to: localhost
  slurp:
    src: "{{ passphrase_file }}"
  register: passphrase_content

- name: "Retrieve GPG key ID from control machine"
  delegate_to: localhost
  slurp:
    src: "{{ key_id_file }}"
  register: key_id_content
- name: "Load GPG passphrase into gpg-agent on target"
  shell: |
    echo RELOADAGENT | gpg-connect-agent
    echo "{{ passphrase_content.content | b64decode }}" | \
    gpg-preset-passphrase --preset --passphrase-fd 0 {{ key_id_content.content | b64decode }}
  args:
    executable: /bin/bash


- name: "Export packages for specified releases"
  shell: "reprepro -b /var/www/repos/apt/{{ item }}/ export"
  loop: "{{ releases }}"
  register: export_result
  ignore_errors: yes